core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("pages/", include("pages.urls")), 
]

pages/urls.py
from django.urls import path
from . import views 

app_name = "pages"
urlpatterns = [
    path("", views.AllKeyWords.as_view(), name="all_keywords"),
    path("<int:page_num>/", views.json_paginated, name="json"),
    path("page/<int:page_num>", views.PaginatorTryouts.as_view(), name="page_view"),
]

pages/models.py
from django.db import models

# Create your models here.
class Keyword(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    

pages/views.py
# django imports
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.core.paginator import Paginator
from django.http import JsonResponse

# project imports
from . import models


class AllKeyWords(ListView):
    model = models.Keyword 
    template_name = "pages/all-keywords.html"
    context_object_name = "keywords"
    paginate_by = 5


def json_paginated(request, page_num=1):
    if request.method == "GET":
        per_page = request.GET.get("per_page", 5)

        object_list = models.Keyword.objects.all()
        paginator = Paginator(object_list, per_page)

        page_obj = paginator.get_page(page_num)

        data = [{"name": kw.name } for kw in page_obj.object_list]

        payload = {
            "page": {
                "current": page_obj.number,
                "has_previous": page_obj.has_previous(),
                "has_next": page_obj.has_next(),
            },
            "data": data
        }

    return JsonResponse(payload)


class PaginatorTryouts(TemplateView):
    template_name = "pages/keywords-page.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # read get parameters
        startswith = self.kwargs.get("startswith", "")
        per_page = self.kwargs.get("per_page", 5)
        page_num = self.kwargs.get("page_num", 1)

        # create filtered query
        keywords = models.Keyword.objects.filter(name__startswith=startswith)
        paginator = Paginator(keywords, per_page=per_page)
        page_obj = paginator.get_page(page_num)

        context["keywords"] = [ keyword.name for keyword in page_obj.object_list]

        payload = {
            "page": {
                "current": page_obj.number,
                "has_next": page_obj.has_next(),
                "has_previous": page_obj.has_previous(),
            },
            "data": context["keywords"],
        }

        return payload
    

pages/templates/pages/all-keywords.html
{% extends 'pages/base.html' %}

{% block content %}
    {% for keyword in keywords %}
        <p>{{ keyword }}</p>
    {% endfor %}
{% endblock content %}

pages/templates/pages/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    {% endblock content %}
    
</body>
</html>

pages/templates/pages/keywords-page.html
{% extends 'pages/base.html' %}

{% block content %}
    <h2>Your results</h2>
    {% for keyword in data %}
        <p>{{ keyword }}</p>
    {% endfor %}

    {% if page.has_previous == True %}
        <div class="link">
            <a href="{% url 'pages:page_view' page.current|add:'-1' %}">Previous</a>
        </div>
    {% endif %}
    <div class="link">
        <a href="{% url 'pages:page_view' page.current %}">Current</a>
    </div>
    {% if page.has_next == True %}
        <div class="link">
            <a href="{% url 'pages:page_view' page.current|add:'1' %}">Next</a>
        </div>
    {% endif %}
{% endblock content %}